export class CharacterDetails {
  constructor(
    public active: boolean,
    public id: number,
    public stationId: number,
    public stationName: string,
    public gender: string,
    public initialsName: string,
    public name: string,
    public relationName: string,
    public guardianRelation: string,
    public fatherHusbandName: string,
    public mobileno: string,
    public districtId: number,
    public districtName: string,
    public villageLocality: string,
    public postOffice: string,
    public panchayat: string,
    public wardNumber: string,
    public dob: Date,
    public durationStay: string,
    public durationIn: string,
    public maritalStatus: string,
    public pinCode: string,
    public aadharNumber: string,
    public adharCardFile: string,
    public signImage: string,
    public userImage: string,
    public type: string,
    public comments: string,
    public addressProof: string,
    public addressProofImage: string,
    public identityProo: string,
    public identityProofImage: string,
    public addressProofOther: string,
    public addressProofOtherImage: string,
    public identityProofOther: string,
    public identityProofOtherImage: string,
    public otherProofOther: string,
    public otherProofOtherImage: string,
    public reportedBy: string,
    public updateStatus: string,
    public status: string,
    public stationIds: number[],
    public fromDate: string,
    public toDate: string
  ) {}
}
