export class CitizenReport {
  constructor(
    public active: boolean,
    public id: number,
    public districtId: number,
    public districtName: string,
    public otherDistrict: string,
    public stationId: number,
    public stationName: string,
    public citizenId: number,
    public citizenName: string,
    public citizenAddress: string,
    public emailid: string,
    public mobileNo: number,
    public reportType: string,
    public modelType: string,
    public modelName: string,
    public modelColor: string,
    public modelNumber: string,
    public area: string,
    public engineNo: string,
    public modelInvoice: string,
    public reportFor: string,
    public vehicleType: string,
    public imeiNumber: string,
    public chassisNumber: string,
    public lostFoundDistrict: string,
    public lostFoundStation: string,
    public invoiceFile: string,
    public lostImage: string,
    public lostImageString: string,
    public citizenDate: string,
    public reportedBy: string,
    public reportStatius: string,
    public createdDateINfo: string,
    public updateStatus: string,
    public status: string,
    public otherInfo: string,
    public reportState: string,
    public otherInfoName: string,
    public firnoDate: string,
    public sectionFirLoged: string,
    public citizenFather: string
  ) {}
}
