export class DeadPerson {
  constructor(
    public active: boolean,
    public id: number,
    public stationId: number,
    public stationName: string,
    public missingName: string,
    public missingImage: string,
    public missingGender: string,
    public missingAge: number,
    public missingHieght: number,
    public missingColor: string,
    public missingSign: string,
    public missingArea: string,
    public missingDate: string,
    public districtId: number,
    public districtName: string,
    public missingState: string,
    public updateStatus: string,
    public status: string,
    public fatherName: string,
    public dateOfMissing: string,
    public wearnigClooth: string,
    public nationality: string,
    public motherName: string,
    public religion: string,
    public firnoDate: string,
    public sectionFirLoged: string,
    public type: string,
    public mobileNo: number,
    public address: string,
    public deathCause: string
  ) {}
}
