export class DistrictDetail {
  constructor(
    public active: boolean,
    public id: number,
    public districtId: number,
    public fullName: string,
    public headAddress: string,
    public email: string,
    public contactNo: number,
    public mobileNo: number,
    public visitorsNumber: string,
    public dgpImage: string,
    public dgpName: string,
    public spImage: string,
    public spName: string,
    public language: string,
    public logo: string,
    public gplayLink: string,
    public downloadLink: string,
    public qrCode: string,
    public twitterLink: string,
    public youtubeLink: string,
    public fbLink: string,
    public address: string,
    public mapUrl: string,
    public aboutSp: string,
    public aboutUs: string,
    public appInstalled: string,
    public isCharacter: boolean,
    public isCharacterStatusCheck: boolean,
    public isCharacterType: string,
    public extraPersonName: string,
    public extraPersonPosition: string,
    public extraPersonImage: string
  ) {}
}
