export class Leave {
  constructor(
    public active: boolean,
    public acceptRejectDate: string,
    public agreeReject: number,
    public applyDate: string,
    public creationDate: string,
    public currentPosting: string,
    public districtId: number,
    public districtName: string,
    public id: number,
    public idInfo: number,
    public leaveApprover: string,
    public leaveApproverComment: string,
    public leaveDescription: string,
    public leaveEndDate: string,
    public leaveManager: string,
    public leaveManagerComment: string,
    public leaveNoOffDays: number,
    public leaveReason: string,
    public leaveStartDate: string,
    public leaveStatus: string,
    public leaveTitle: string,
    public leaveType: string,
    public leavetypeId: number,
    public leavetypeName: string,
    public resourceBatchId: number,
    public resourceDesg: string,
    public resourceId: number,
    public resourceMobileNo: string,
    public resourceName: string,
    public stationId: number,
    public stationName: string,
    public updateStatus: string,
    public userId: number,
  ) {}
}
