export class ReplyComplaint {
  constructor(
    public active: boolean,
    public id: number,
    public appVisitorsId: number,
    public appointmentId: number,
    public approverComment: string,
    public grSectionId: number,
    public characterDetailsId: number,
    public commissionId: number,
    public complaintId: number,
    public courtId: number,
    public deadId: number,
    public foundPersonId: number,
    public itemOrderId: number,
    public ecommunicationId: number,
    public medicineMasterId: number,
    public leaveId: number,
    public missingPersonId: number,
    public passportId: number,
    public policestationId: number,
    public procecutionId: number,
    public replyDescription: string,
    public replyFrom: number,
    public replyStatus: string,
    public rtiId: number,
    public sectionId: number,
    public userAppVisitorsId: number,
    public username: string,
    public visitor_id: number,
    public citizenReportId: number,
    public gpoId: number,
    public gfpoId: number
  ) {}
}
