export class ReplyComment {
  constructor(
    public active: boolean,
    public appointmentId: number,
    public grSectionId: number,
    public characterVerificationId: number,
    public citizenReportId: number,
    public commissionId: number,
    public complaintId: number,
    public courtId: number,
    public createdBy: number,
    public createdDate: string,
    public deadId: number,
    public dispatchNo: string,
    public dispatchNum: string,
    public districtMemoNo: string,
    public ecommunicationDispatchId: number,
    public ecommunicationId: number,
    public foundPersonId: number,
    public id: number,
    public leaveId: number,
    public missingPersonId: number,
    public passportVerificationId: number,
    public policeStationId: number,
    public procecutionId: number,
    public reciptNo: string,
    public replyDate: string,
    public replyDescription: string,
    public replyFrom: number,
    public replyImage: string,
    public replyStatus: string,
    public rtiId: number,
    public sharedDocId: number,
    public updateStatus: string,
    public updatedBy: number,
    public updatedDate: string,
    public userId: number,
    public visitorId: number,
    public gpoId: number,
    public gfpoId: number
  ) {}
}
