import { Component } from '@angular/core';

@Component({
  selector: 'app-holyday-list',
  templateUrl: './holyday-list.component.html',
  styleUrls: ['./holyday-list.component.scss']
})
export class HolydayListComponent {
  holidays = [

      { srNo: 1, name: "New Year's Day", description: "Beginning of the year", date: "January 1", type: "Restricted Holiday" },
      { srNo: 2, name: "Lohri", description: "A Punjabi festival, celebrated with bonfires and traditional folk songs.", date: "January 13", type: "Restricted Holiday" },
      { srNo: 3, name: "Makar Sankranti", description: "", date: "January 14", type: "Restricted Holiday" },
      { srNo: 4, name: "Pongal", description: "", date: "January 15", type: "Restricted Holiday" },
      { srNo: 5, name: "Guru Govind Singh Jayanti", description: "", date: "January 17", type: "Restricted Holiday" },
      { srNo: 6, name: "Hazarat Ali's Birthday", description: "", date: "January 25", type: "Restricted Holiday" },
      { srNo: 7, name: "Republic Day", description: "", date: "January 26", type: "Gazetted Holiday" },
      { srNo: 8, name: "Lunar New Year", description: "", date: "February 10", type: "Observance" },
      { srNo: 9, name: "Vasant Panchami", description: "", date: "February 14", type: "Restricted Holiday" },
      { srNo: 10, name: "Valentine's Day", description: "", date: "February 14", type: "Observance" },
      { srNo: 11, name: "Shivaji Jayanti", description: "", date: "February 19", type: "Restricted Holiday" },
      { srNo: 12, name: "Guru Ravidas Jayanti", description: "", date: "February 24", type: "Restricted Holiday" },
      { srNo: 13, name: "Maharishi Dayanand Saraswati Jayanti", description: "", date: "March 6", type: "Restricted Holiday" },
      { srNo: 14, name: "Maha Shivaratri/Shivaratri", description: "", date: "March 8", type: "Restricted Holiday" },
      { srNo: 15, name: "Ramadan Start (Tentative Date)", description: "", date: "March 12", type: "Observance" },
      { srNo: 16, name: "March Equinox", description: "", date: "March 20", type: "Season" },
      { srNo: 17, name: "Holika Dahana", description: "", date: "March 24", type: "Restricted Holiday" },
      { srNo: 18, name: "Holi", description: "", date: "March 25", type: "Gazetted Holiday" },
      { srNo: 19, name: "Dolyatra", description: "", date: "March 25", type: "Restricted Holiday" },
      { srNo: 20, name: "Maundy Thursday", description: "", date: "March 28", type: "Observance, Christian" },
      { srNo: 21, name: "Good Friday", description: "", date: "March 29", type: "Gazetted Holiday" },
      { srNo: 22, name: "Easter Day", description: "", date: "March 31", type: "Restricted Holiday" },
      { srNo: 23, name: "Jamat Ul-Vida (Tentative Date)", description: "", date: "April 5", type: "Restricted Holiday" },
      { srNo: 24, name: "Chaitra Sukhladi", description: "", date: "April 9", type: "Restricted Holiday" },
      { srNo: 25, name: "Ugadi", description: "", date: "April 9", type: "Restricted Holiday" },
      { srNo: 26, name: "Gudi Padwa", description: "", date: "April 9", type: "Restricted Holiday" },
      { srNo: 27, name: "Ramzan Id/Eid-ul-Fitar (Tentative Date)", description: "", date: "April 11", type: "Gazetted Holiday" },
      { srNo: 28, name: "Ramzan Id/Eid-ul-Fitar (Tentative Date)", description: "", date: "April 11", type: "Muslim, Common local holiday" },
      { srNo: 29, name: "Vaisakhi", description: "", date: "April 13", type: "Restricted Holiday" },
      { srNo: 30, name: "Mesadi / Vaisakhadi", description: "", date: "April 14", type: "Restricted Holiday" },
      { srNo: 31, name: "Ambedkar Jayanti", description: "", date: "April 14", type: "Observance" },
      { srNo: 32, name: "Rama Navami", description: "", date: "April 17", type: "Gazetted Holiday" },
      { srNo: 33, name: "Mahavir Jayanti", description: "", date: "April 21", type: "Gazetted Holiday" },
      { srNo: 34, name: "First day of Passover", description: "", date: "April 23", type: "Observance" },
      { srNo: 35, name: "International Worker's Day", description: "", date: "May 1", type: "Observance" },
      { srNo: 36, name: "Birthday of Rabindranath", description: "", date: "May 8", type: "Restricted Holiday" },
      { srNo: 37, name: "Mothers' Day", description: "", date: "May 12", type: "Observance" },
      { srNo: 38, name: "Buddha Purnima/Vesak", description: "", date: "May 23", type: "Gazetted Holiday" },
      { srNo: 39, name: "Fathers' Day", description: "", date: "June 16", type: "Observance" },
      { srNo: 40, name: "Bakrid/Eid ul-Adha (Tentative Date)", description: "", date: "June 17", type: "Gazetted Holiday" },
      { srNo: 41, name: "June Solstice", description: "", date: "June 21", type: "Season" },
      { srNo: 42, name: "Rath Yatra", description: "", date: "July 7", type: "Restricted Holiday" },
      { srNo: 43, name: "Muharram/Ashura (Tentative Date)", description: "", date: "July 17", type: "Gazetted Holiday" },
      { srNo: 44, name: "Guru Purnima", description: "", date: "July 21", type: "Observance" },
      { srNo: 45, name: "Friendship Day", description: "", date: "August 4", type: "Observance" },
      { srNo: 46, name: "Independence Day", description: "", date: "August 15", type: "Gazetted Holiday" },
      { srNo: 47, name: "Parsi New Year", description: "", date: "August 15", type: "Restricted Holiday" },
      { srNo: 48, name: "Raksha Bandhan (Rakhi)", description: "", date: "August 19", type: "Restricted Holiday" },
      { srNo: 49, name: "Janmashtami", description: "", date: "August 26", type: "Gazetted Holiday" },
      { srNo: 50, name: "Janmashtami (Smarta)", description: "", date: "August 26", type: "Observance" },
      { srNo: 51, name: "Ganesh Chaturthi/Vinayaka Chaturthi", description: "", date: "September 7", type: "Restricted Holiday" },
      { srNo: 52, name: "Onam", description: "", date: "September 15", type: "Restricted Holiday" },
      { srNo: 53, name: "Milad un-Nabi/Id-e-Milad (Tentative Date)", description: "", date: "September 16", type: "Gazetted Holiday" },
      { srNo: 54, name: "September Equinox", description: "", date: "September 22", type: "Season" },
      { srNo: 55, name: "Mahatma Gandhi Jayanti", description: "", date: "October 2", type: "Gazetted Holiday" },
      { srNo: 56, name: "First Day of Sharad Navratri", description: "", date: "October 3", type: "Observance, Hinduism" },
      { srNo: 57, name: "First Day of Durga Puja Festivities", description: "", date: "October 9", type: "Observance, Hinduism" },
      { srNo: 58, name: "Maha Saptami", description: "", date: "October 10", type: "Restricted Holiday" },
      { srNo: 59, name: "Maha Navami", description: "", date: "October 11", type: "Restricted Holiday" },
      { srNo: 60, name: "Maha Ashtami", description: "", date: "October 11", type: "Restricted Holiday" },
      { srNo: 61, name: "Dussehra", description: "", date: "October 12", type: "Gazetted Holiday" },
      { srNo: 62, name: "Maharishi Valmiki Jayanti", description: "", date: "October 17", type: "Restricted Holiday" },
      { srNo: 63, name: "Karaka Chaturthi (Karva Chauth)", description: "", date: "October 20", type: "Restricted Holiday" },
      { srNo: 64, name: "Halloween", description: "", date: "October 31", type: "Observance" },
      { srNo: 65, name: "Naraka Chaturdasi", description: "", date: "October 31", type: "Restricted Holiday" },
      { srNo: 66, name: "Diwali/Deepavali", description: "", date: "October 31", type: "Gazetted Holiday" },
      { srNo: 67, name: "Govardhan Puja", description: "", date: "November 2", type: "Restricted Holiday" },
      { srNo: 68, name: "Bhai Duj", description: "", date: "November 3", type: "Restricted Holiday" },
      { srNo: 69, name: "Chhat Puja (Pratihar Sashthi/Surya Sashthi)", description: "", date: "November 7", type: "Restricted Holiday" },
      { srNo: 70, name: "Guru Nanak Jayanti", description: "", date: "November 15", type: "Gazetted Holiday" },
      { srNo: 71, name: "Guru Tegh Bahadur's Martyrdom Day", description: "", date: "November 24", type: "Restricted Holiday" },
      { srNo: 72, name: "December Solstice", description: "", date: "December 21", type: "Season" },
      { srNo: 73, name: "Christmas Eve", description: "", date: "December 24", type: "Restricted Holiday" },
      { srNo: 74, name: "Christmas", description: " Christmas Day is on 25th December", date: "December 25", type: "Gazetted Holiday" },
      { srNo: 75, name: "First Day of Hanukkah", description: "", date: "December 26", type: "Observance" },
      { srNo: 76, name: "New Year's Eve", description: "", date: "December 31", type: "Observance" }



  ];
}
